### ISSUE TITLE
MODEL_NAME in config.json is not applied to the API call

### ISSUE THREAD

**Issue by masanorihirano** [k-takano0423/BiClass-Definition-Generator#1]
https://github.com/k-takano0423/BiClass-Definition-Generator/blob/main/config_file/config.json#L4

Here, MODEL_NAME is defined.

But, it is not applied to the API calls.

**Comment by masanorihirano** [comment]
https://github.com/k-takano0423/BiClass-Definition-Generator/blob/29a4b7f651a7de800d5dc63aca7facdfd82b55a1/src/ABCD_Gen.py#L124
This seems missing "model_name"

**Comment by k-takano0423** [comment]
I sincerely appreciate you for finding my mistake and suggesting a fix.
We would like to incorporate your corrections.
